server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_source
    password: 1234
    username: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swagger 启动 空指针错误
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.briup.product_source.bean.basic
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名自动映射
    cache-enabled: true
logging:
  level:
    com.briup.dao: debug
    com.zaxxer: error
swagger:
  enabled: true   #开启swagger
  base-package: com.briup.product_source.web.controller   #扫描注解的包，生成API文档
  title: 智慧农业溯源平台
  contact:
    email: zzx@briup.com
    name: zzx
    url: www.briup.com
  description: 这是智慧农业溯源
pagehelper:
  helper-dialect: mysql   #指定分页语句方言（自动识别）
  reasonable: true #分页参数合理化：pageNum<=0　第一页　pageNum>总页数 最后一页