server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_source
    password: 1234
    username: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swagger 启动 空指针错误
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #全局时间配置
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.briup.product_source.bean
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名自动映射
    cache-enabled: true
logging:
  level:
    com.briup.dao: debug
    com.zaxxer: error
    org.springframework.jdbc: debug #开启事务管理日志
swagger:
  enabled: true   #开启swagger
  base-package: com.briup.product_source.web.controller   #扫描注解的包，生成API文档
  title: 智慧农业溯源平台
  contact:
    email: zzx@briup.com
    name: zzx
    url: www.briup.com
  description: 这是一个ssm项目
  authorization:
    key-name: token # 认证的请求参数名，swagger ui 默认是大写的
    auth-regex: ^(?!\/login$).+  #除了匹配/login外的任意字符串
pagehelper:
  helper-dialect: mysql   #指定分页语句方言（自动识别）
  reasonable: true #分页参数合理化：pageNum<=0　第一页　pageNum>总页数 最后一页

oss:
  accessKey: byqk2cRm3JcXk2ixy1khme2cQsM_nn2PZly2b8y_
  secretKey: 6L9KcM_ePlvIYQ5FmEKx5DBm3TdtBWLIbN3GxMqX
  bucket: product-source-666

#配置文件上传保存的服务器目录
upload:
  filePath: C:\Users\zzx\Desktop\imgs\   #文件上传保存目录
  serverPath: http://localhost:8000/imgs/  #访问图片服务器路径
# 配置文件上传和下载配置信息
file:
  upload:
    dir: C:\Users\zzx\Desktop\imgs\  #保存目录
    ip: 127.0.0.1   #图片服务器地址
    port: 8000      #图片服务器端口号
    url: /imgs    #图片服务器访问url
  download: 文件下载（暂定）

